trigger:
  - master

pool:
  name: Default 

variables:
  ARM_CLIENT_ID: $(servicePrincipalId)
  ARM_CLIENT_SECRET: $(servicePrincipalKey)
  ARM_SUBSCRIPTION_ID: $(subscriptionId)
  ARM_TENANT_ID: $(tenantId)

stages:
  - stage: TerraformInit
    jobs:
      - job: Init
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-rm-terraform1'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(System.DefaultWorkingDirectory)/infra
              inlineScript: |
                terraform init

  - stage: TerraformPlan
    dependsOn: TerraformInit
    jobs:
      - job: Plan
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-rm-terraform1'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(System.DefaultWorkingDirectory)/infra
              inlineScript: |
                terraform plan -out=tfplan

  - stage: TerraformApply
    dependsOn: TerraformPlan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Apply
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-rm-terraform1'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(System.DefaultWorkingDirectory)/infra
              inlineScript: |
                terraform apply -auto-approve tfplan
