trigger:
  branches:
    include:
      - master
      - main
  paths:
    include:
      - backend/*
      - frontend/*

pool:
  name: Default  # Use your self-hosted agent pool name

variables:
  DOCKER_BUILDKIT: 1

stages:
  - stage: BuildAndTest
    jobs:
      - job: Backend
        displayName: "Backend: Build & Test"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'

          - task: Docker@2
            displayName: 'Build backend image'
            inputs:
              command: build
              repository: pkotopoulis/quote-backend
              Dockerfile: backend/quote-api/Dockerfile
              tags: latest

          - script: |
              pip install -r backend/quote-api/requirements.txt
              pytest backend/quote-api/
            displayName: "Run Pytest for backend"

      - job: Frontend
        displayName: "Frontend: Build"
        steps:
          - task: Docker@2
            displayName: 'Build frontend image'
            inputs:
              command: build
              repository: pkotopoulis/quote-frontend
              Dockerfile: frontend/Dockerfile
              tags: latest
